### ISSUE TITLE
Errors after running GPU version

### ISSUE THREAD

**Issue by HyperLemons** [Crivella/ocr_translate#11]
![image](https://github.com/Crivella/ocr_translate/assets/36387099/40b387c1-2fc6-4682-b7b9-4185538d2566)

Program will show the same errors when running through regular cmd with administrator instead of Terminal (the program used in the screenshot), but instantly crashes as soon as the errors appear.

Using a laptop with i7-7700HQ and GTX 1050 (2GB) connected to an external monitor.

**Comment by Crivella** [comment]
Thanks for the opening an issue @HyperLemons 

That error indicates that Django (the server) is somehow unable to open the database (it should not be hardware related).
Which version of the server are you running? (The error is happening at line 62 in run_server.py, but the what is happening at that line changed from 0.2.0 to 0.3.2).
I would guess 0.3.2 since there at line 62 is the first command that accesses the DB in the script, but to be sure



Did the server work for you with a previous version of the tool or using the CPU variant of the same version?

I tried to reproduce the error (on 0.3.2) by simulating a corrupt database, or a read-only database, but Django actually gives more specific errors in that case than the one you are getting.
I also tried to run two instances of the server at once, but both are able to access the sqlite database without crashing.

Could you provide this further information/tests
- Does the folder `%userprofile%/.ocr_translate` exist (you can copy this in file explorer and get a pop-up error if it doesn't)
- Do you have a `db.sqlite3` file under  `%userprofile%/.ocr_translate`?
- If not can you try creating a random file there (to see if someone the folder is locked)
- If yes can you try renaming (or deleting but you will lose the translation you already performed in case you care about it) it and see if the error persists?
- If renaming/deleting fails because the file is busy easiest thing I would suggest to reboot (could be many thing from OS to installed programs that is causing it)
- If renaming/deleting succeeds and it fixes nice, but if you want you can try to open the old `db.sqlite3` with a tool like https://sqlitebrowser.org/ to see if it works or send it to me to check (Maybe i can open a discord for the tool so you can send it to me directly...) (PS the info in the DB is the HASH of the images and the results of the OCR/translation in case you want to judge whether to send it or not)
- If renaming/deleting succeeds and the server recreate the database, but still give the same error, I will have to investigate further

**Comment by Crivella** [comment]
@pylofe @HyperLemons Thanks both for the report

The `run_server` script is failing to create the `%userprofile%/.ocr_translate folder if it does not exists already due to [this line](https://github.com/Crivella/ocr_translate/blob/fbb543599d332873fcf9d817257c6fea7af237c4/run_server.py#L42) only creating the top_level folder.

I will fix this in the next release of the code.

In the meanwhile, manually creating the folder and launching the EXE should work (let me know in case it doesn't)
