### ISSUE TITLE
Error after installing via github

### ISSUE THREAD

**Issue by pylofe** [Crivella/ocr_translate#12]
So I have tried installing the application via the github method:
This is windows 11 amd cpu, nvidia rtx 3050 ti, and for the application should be 0.3.2 release

I have tried both cpu and gpu versions and both do run as I reach the
Django version 4.2.6, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:4000/
line.

However once you are on the extention you are not able to select things as shown here:
![image](https://github.com/Crivella/ocr_translate/assets/149007083/c700b564-317c-40fd-8565-269ff2f875d3)

Here were the exact steps done to install it: ( this is for the cuda version)
virtualenv ocr_translate_env
.\ocr_translate_env\Scripts\activate
git clone https://github.com/Crivella/ocr_translate.git
cd ocr_translate
pip install -r requirements-torch-cuda.txt
pip install -r requirements.txt

--once everything was intalled ran these on the command shell

python manage.py migrate
python manage.py runserver 4000
then 
once at the end got this error
System check identified some issues:

WARNINGS:
?: (staticfiles.W004) The directory 'C:\Users\User\Desktop\OCR\ocr_translate\static' in the STATICFILES_DIRS setting does not exist.

System check identified 1 issue (0 silenced).
October 25, 2023 - 14:41:33
Django version 4.2.6, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:4000/
Quit the server with CTRL-BREAK.

And as per the prvious image, it does turn green for the http part. And the image on the page does get surrounded by a red box, but just not able to choose the language etc options.

I checked the ocr_translate folder and the static folder is not there.

For context I already had tessarct ocr and such on my computer from a previous project, but that should have been in an env folder.

**Comment by pylofe** [comment]
oops, forgot to enable the two env variables at the begining as well as create the folder that was missing. This was for the version right before this one.

 It works now, however what does it mean when its red for the model?
 
![image](https://github.com/Crivella/ocr_translate/assets/149007083/e62ca81a-f20c-4255-acbb-337e6492f0ed)

**Comment by Crivella** [comment]
Thanks for opening the issue @pylofe 

- Did you do this as a clean install or did you migrate an existing database?

As a clean install of 0.3.2 with the command you reported you should actually see no models available (the actual model setup has been moved into  plugins since 0.3.x)
What i expect is that you migrated a previous existing database from 0.2.x to 0.3, so you still see the models, but the main app alone does not know how to load/use them.

If this is the case i would refer you to [this page in the documentantion](https://crivella.github.io/ocr_translate/user/index.html#known-validated-plugins) for the plugins you need (all of them but the google one) (they have the same logic and workflow that was implemented when the code was more monolithic, just split for easier user customization and maintainability)

If this is not the case i would suggest also setting these 2 environment variables before running the server:
- DJANGO_DEBUG="true"
- DJANGO_LOG_LEVEL="DEBUG"
to get a more detailed report in the server terminal that you can send here

**Comment by pylofe** [comment]
So I did delete the application(the one that was working was a previous version), and then reistalled to the newest version 0.3.2 using git, and as you mentioned the models are not present in that one. I will try to do the plugins and get back on that too see if it works.

**Comment by pylofe** [comment]
Great, it works now, you can close it if you like!
I just noticed that ocr_translate-tesseract and ocr_translate-google have same plugin app name for the readme sections, not sure if thats a typo.

**Comment by Crivella** [comment]
> Also noticed that ocr_translate-tesseract and ocr_translate-google have same plugin app name for the readme sections, not sure if thats a typo.

Oh yeah thanks that is definitely a copy-paste error.

Will close the issue than cheers.
