### ISSUE TITLE
Can't get it to work. Just getting blurred image right after clicking the icon on the address bar

### ISSUE THREAD

**Issue by himouto** [Crivella/ocr_translate#25]
I'm using run_server-gpu version. The fields are color green but when I click the icon on the address bar nothing happens just blurred image.

I'm getting this error when using kha-white/manga_ocr_base: "Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration." so I tested tesseract and the results are the same.

I tested the cpu version and same results - after clicking the add-on icon on the address bar nothing happens it just blurs the 
image. Tried refreshing the tab while the icon is green still no translation - just blurred image with red outline. Check screenshot below:

![Screenshot 2024-01-25 133030](https://github.com/Crivella/ocr_translate/assets/14362301/59805720-6228-4f12-a105-1d863d9a01b2)

**Comment by Crivella** [comment]
Hi @himouto thanks for opening this issue.

Would it be possible for you to attach also the log shown in the server window?
Ideally with the [environment variable](https://crivella.github.io/ocr_translate/user/envs.html) `DJANGO_LOG_LEVEL` set to `DEBUG`, but also the basic one would help.

Need to understand what is going on as it is kind of weird that also tesseract would give you the same error.

Also i assume you are running using the release file. (I see you can see the advanced options tab in the extension and languages written in extended format so it should be the latest version). Is this your first time trying to run the server or did it ever work for you before with previous versions?

**Comment by himouto** [comment]
![Uploading Screenshot 2024-01-26 075933.png…]()

**Comment by Crivella** [comment]
I will have to investigate and try to reproduce the bug, in my case starting from a fresh install of the server (using the release file v0.5.1) it seems to be working fine.
The error you see I think is due to some update to the online model, but it's not relevant. (You can see it in my log as well)

![image](https://github.com/Crivella/ocr_translate/assets/34096612/08a6ca72-cc85-4783-9c12-6f4d5cad3cd8)

![image](https://github.com/Crivella/ocr_translate/assets/34096612/2792b158-b1da-47a1-9f7d-330cb6d240bd)

It is kind of weird you don't even see the beginning of the translation starting, but it shouldn't be a a firewall issue since you are able to set the language and models properly

One thing you could try is delete the `%userprofile%/.ocr_translate` folder and try to start the server

PS: that website does have images that have place-ins replaces by JS when you scroll over them, i still have to implement handling of this in the extension as well

**Comment by Crivella** [comment]
PS: This would really help, could you give me the result of the following (see screenshot for help, in my case i simulated a server error by not loading any models):

- Start the server
- Go to the page you want to translate
- Press F12
- Click on console
- Start the translation
- Once the red border appears there will be some log of the errors
  - Expand the last object
  - Expand response
  - Either copy here the entire thing or at minimum, the  `data` field that contains the error being sent from the server to the extension

![image](https://github.com/Crivella/ocr_translate/assets/34096612/56e96ee9-f04c-4351-9be2-0b0a6de72e88)

**Comment by himouto** [comment]
![Screenshot 2024-01-26 114348](https://github.com/Crivella/ocr_translate/assets/14362301/aab8b51d-f10a-4687-9a4f-2c0f86a922b5)

Can't see a response in the console. I did a fresh re-install of the add-on and it's still the same - after "GET / HTTP/1.1 200 3776" line in the server window it gets stuck there. I'm using the latest nvidia driver which just updated 2 days ago if that changes anything and Python 3.10.6 for my A1111 stable diffusion setup

**Comment by himouto** [comment]
Tested with tesseract:
![Screenshot 2024-01-26 123557](https://github.com/Crivella/ocr_translate/assets/14362301/6bf928ad-7ab3-4a2e-81cf-e5552e9babfb)

Also no response under request. Is there any chance ublock is behind this like it's blocking the addon functions not the manga website since I tested turning it off for this site but same results

**Comment by himouto** [comment]
There's no >response under Object. I only see >config, >request and >prototype. In the server window it's stuck on "django.server.basehttp - "GET / HTTP/1.1"" - tried waiting it out for over 10 minutes. I have a decent hardware RTX 3070 with the latest driver so it shouldn't take that long.

**Comment by Crivella** [comment]
So I can tell it' not a problem with

- drivers version
- firefox version
- ublock

as i am running the same.

Also no point in waiting, once there is a red corner it means there was an error (only blurred with no border means it is still doing something)

From what you have shown, it looks like the [popup.js](https://github.com/Crivella/ocr_extension/blob/master/src/popup.js) script is working fine (the one that is doing the setting of the language and models) but the [content.js](https://github.com/Crivella/ocr_extension/blob/master/src/content.js) is not.

Weirdly enough you don't even get the URL in the request you have shown (I can simulate the same error by running the translation without the server open, but i see the URL where the image would be sent)

![image](https://github.com/Crivella/ocr_translate/assets/34096612/78006841-f855-4843-aa05-2fd1ea0b8277)

I think something is blocking communication between the `content.js` and `background.js`/`popup.js` scripts because the endpoint is blank at the start but is set the first time you open the popup (the menu you get when you click on the extension).

I will check this evening what could be causing this and get back at you

**Comment by Crivella** [comment]
If you don't mind could you right click on the trace object and click `Copy Object` and paste the result here, i want to check also the content of the `config` part where you should be able to see the URL being used.

Unfortunately I am not sure the problem is what i was thinking before.
If it was just communication between the extension components and the `ENDPOINT` was empty you should get a domain exception because of trying to open `undefined/run_ocrtsl/` as an URL (simulated by running a modified version of the extension where i manually introduced the error).

Unfortunately without having the system under my hand or being able to reproduce the bug it is kind of hard to get to the root of it.
Given the server log you have shown I can for sure that requests for translation are never reaching it. 
Either the extension is doing something wrong and not managing to send a request, or something external is blocking requests being sent by `content.js`  but not `popup.js`.

**Comment by himouto** [comment]
Figured it out. It was uBlock Origin, I disabled it and restarted the server window and it's now working properly

![Screenshot 2024-01-27 083526](https://github.com/Crivella/ocr_translate/assets/14362301/64f96c09-11d9-49d4-af3d-d7c1345f82dc)

Now to figure out why it's doing this... I tried whitelisting 127.0.0.1 and 127.0.0.1:4000 on ublock's Trusted sites but it's still breaking the extension

I'm getting these errors on console when ublock is enabled.. not sure if they're related

![Screenshot 2024-01-27 083754](https://github.com/Crivella/ocr_translate/assets/14362301/5200437e-2cd9-4d30-a904-55957bb237c3)

**Comment by himouto** [comment]
Disable Javascript is not enabled on my ublock settings so idk what's causing this... not sure if any of the Filters are the culprit but completely disabling the extension temporarily fixes the issue
![Screenshot 2024-01-27 085631](https://github.com/Crivella/ocr_translate/assets/14362301/555ac341-e955-4404-adb8-cd84a7926d14)

**Comment by Crivella** [comment]
Good that you figured it out.
Weird that it was uBlock as I also have it and never had to add any whitelisting for it work.

The other errors you've shown are not related.
What is being blocked is not the JS itself but the [XHR](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) request from the extension to the server.

One possible long term solution would be for me to modify the extension so all XHR requests are originating either from the `background.js` or `popup.js` which other extension should not be able to interfere with (`content.js` is injected and running inside the tab).

For now I will mark this as closed and add a note in the README.

Feel free to open a new issue or rewrite here in case something else comes up.

Hope you will enjoy the extension

**Comment by himouto** [comment]
Thank you for the help. It's a very good extension.
