### ISSUE TITLE
Error 500 when i try to download plugins  

### ISSUE THREAD

**Issue by khalidiop** [Crivella/ocr_translate#39]
![image](https://github.com/user-attachments/assets/e906724e-2097-45d1-a9fc-04f8268e1eaa)

hello this is the error i get on the server i dont know what to do

**Comment by Crivella** [comment]
Could you give me more information about:

- What system are you running on
- What version of python do you have
- What plugin were you installing
  - Maybe try to install them 1by1 and see if the error happens with them all or only one

**Comment by khalidiop** [comment]
sorry for the late response 

i use windows 10 pro
i am using 3.11.9 pyhton as the instructions was saying 
i tried it downloading 1 by 1 but it failed

**Comment by Crivella** [comment]
Try the following in order to have more debug information:

- edit your `run-user.bat` script to have the following (to enable more log messages)

    ```
    set DJANGO_DEBUG=true
    set DJANGO_LOG_LEVEL=DEBUG
    ```

- Delete your `OCT_BASE_DIR` (if it is not set to a custom value in `run-user.bat`, the default on windows is `%userprofile%\.ocr_translate` which automatically translates to `C:\Users\<your_username>\.ocr_translate`)

- Repeat the install one by one.
  Also you should copy and pase here all the output.
  At least from the last few debug messages and the entire error from `pip` (you posted a piece of it in the screenshot).
  It will show which plugin you are installing and on which sub-package it failed (+ ~how by the pip error message).
  There should be no sensitive data in the logs, worst that could be there is the path to your home directory, feel free to search and replace it out before pasting if you don't want to share it.

Sorry for the trouble, but since i can't reproduce the issue on my machine, i need more information to help you.

**Comment by khalidiop** [comment]
hello  i am sorry but i dont understand a thing of what been said i am not very knowledegable about this stuff
can you explain it as if  i was 5 years old

**Comment by khalidiop** [comment]
![image](https://github.com/user-attachments/assets/c8da4fee-0e95-4732-9b04-0c61ab3a6bc1)
This is the whole error i think (i tried to download the first plugin)

**Comment by khalidiop** [comment]
this is the second plugin screen shot

![image](https://github.com/user-attachments/assets/ccd749ef-9c09-4a11-8b13-18488241647a)

**Comment by khalidiop** [comment]
this one is the last plugin
![image](https://github.com/user-attachments/assets/88b8dae3-6185-455c-b295-154f0979b3ba)

**Comment by Crivella** [comment]
Thanks this should be enough to get started, I will try and see if i can reproduce it

**Comment by Crivella** [comment]
So not really able to reproduce this (will do more testing at home with a Windows machine), but it seems related to

https://stackoverflow.com/questions/34819221/why-is-python-setup-py-saying-invalid-command-bdist-wheel-on-travis-ci

One thing you can try is:

open the `run.bat` file (next to `run-user.bat` that you are launching) with any text editor (also notepad)

around line 48 where you see

```
:skip_venv
:launch
%PYTHON% run_server.py %*
pause
exit /b
```

edit it to add the line 

```
pip install wheel
```

before `%PYTHON%`, at the end it should look like this

```
:skip_venv
:launch
pip install wheel
%PYTHON% run_server.py %*
pause
```

Try to reinstall the plugins that are failing and let me know if it works,
in case i will add this to future releases
exit /b

**Comment by khalidiop** [comment]
it worked thank you very much
